### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by kevinkey619** [Scott8586/bme280-python-mqtt#4]
Hi,

No matter what I try, I can't get the service to start.

May 24 11:51:18 ubuntu systemd[1]: bme280-mqtt.service: Main process exited, code=exited, status=1/FAILURE
May 24 11:51:18 ubuntu systemd[1]: bme280-mqtt.service: Failed with result 'exit-code'.

Note the following line:
PIDFile=/run/bme280_mqtt.pid

When I look in the /run directory, I don't see any bme280_mqtt.pid

Also:

pi@ubuntu:/etc/systemd/system $ /usr/bin/python3 /usr/local/bin/bme280_mqtt_daemon.py
Traceback (most recent call last):
  File "/usr/local/bin/bme280_mqtt_daemon.py", line 326, in <module>
    main()
  File "/usr/local/bin/bme280_mqtt_daemon.py", line 323, in main
    start_bme280_sensor(cmdline_args)
  File "/usr/local/bin/bme280_mqtt_daemon.py", line 200, in start_bme280_sensor
    options.root_topic = mqtt_conf.get(args.section, 'topic')
  File "/usr/lib/python3.9/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.9/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'BME280'
pi@ubuntu:/etc/systemd/system $ 

What am I missing?

**Comment by kevinkey619** [comment]
SOLVED

Oops... I had to create /etc/mqtt.ini  :)

  GNU nano 5.4                                                             mqtt.ini                                                                       
[BME280]
host=localhost 
port=1883
#username=<name> # optional
#password=<pass> # optional
topic="indoor"  
address=0x76
elevation=0
toffset=0 
hoffset=0 
poffset=0 

Now it's working.
